nav:
  - title: 归档
    url: archives/index.html
    icon: fa-archive
    description: 
  - title: 关于
    url: about/index.html
    icon: fa-user
    description: 

notice:
  enabled: false
  content: 
    - 

mobile_menu: true
global_navigation: true

duoshuo_shortname: unnamed42-github
disqus_shortname: 

search: true

busuanzi: true

tag_number: 25
full_content: false

cdn: 
placeholder: 

links:
  - title: Tony
    url: https://tonyzzx.github.io
    description: 美国留学的高富帅
  - title: 不知
    url: http://maokwen.tk
    description: 谜之小伙伴
