keywords: 

nav:
  - title: 归档
    url: archives/index.html
    icon: fa-archive
    description: 
  - title: 关于
    url: about/index.html
    icon: fa-user
    description: 
  - title: 订阅
    url: atom.xml
    icon: fa-rss

notice: 

global_navigation: true

sidebar: true

duoshuo_shortname: unnamed42-github

# Register at https://disqus.com/api/applications to get disqus_api_key
# Use the API Key, not the API Secret
disqus_shortname: # unnamed42-github 
disqus_api_key: #"1PwNiUJfZNlIZGUH0d0ZfKyOBXhdTclO1F9BJqRJDjcrJ5JVGe45C7YAQO0L5lFc"

search: true

busuanzi: true

tag_number: 25
full_content: false

# Provided colors: red, green, blue, purple
color_theme: blue

cdn: 
placeholder: 

mathjax: true

# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero 
creative_commons: by-sa

sns: 
  github: unnamed42
  twitter:
  facebook:
  linkedin:
  googleplus_id: "101538012089625781458"
  steam_id:
  weibo:
  zhihu: huang-wen-rui-74
  tieba: Xelnagaman

buttons:
  base: true
  border: false
  borderless: false
  raised: false
  3d: false
  glowing: false
  dropdown: false
  group: false
  wrapper: false
  shadow: false

links:
  - title: Tony
    url: https://tonyzzx.github.io
    description: 美国留学的高富帅
  - title: 不知
    url: http://maokwen.tk
    description: 谜之小伙伴
